### ISSUE TITLE
Add live example

### ISSUE THREAD

**Issue by khinshankhan** [remcohaszing/codemirror-languageservice#2]
Deploy a live examples so onlookers can view the project. Possibly deploy the example https://github.com/remcohaszing/codemirror-languageservice/tree/main/example to github pages or the sort?

**Comment by remcohaszing** [comment]
I love the enthousiasm!

I wonder if the example isn’t too silly for a live demo though. A more practical real world example would be to integrate an existing language service, but I do like that the current example is minimal and shows off all possible features.

Also I feel like the real value of the current example is the code itself, not necessarily the result. For example, I deploy a demo for [`monaco-yaml`](https://monaco-yaml.js.org). The value there is the visible YAML integration. For `codemirror-languageservice` the value is more abstract: It should be combined with a language service.

Do you have any thoughts on that?

**Comment by khinshankhan** [comment]
I agree though counterpoint: the example source code will continue to be present if there's a viewable page + the fact that there is an example directory means there are concrete examples that could be shown.

Maybe I've misunderstood your point but if the question was showing it with multiple language services, wouldn't that just be multiple demos(?)

**Comment by remorses** [comment]
It would be cool to create a demo with mdx-analyzer

**Comment by remcohaszing** [comment]
The example is now hosted on https://codemirror-languageservice.js.org. I made it a bit fancier, but not too much. I welcome changes to make it a bit nicer (i.e. light mode support), but I want to keep it a somewhat minimal.

> It would be cool to create a demo with mdx-analyzer

I love that suggestion! :heart: But for now I’m leaving that out.
